TesteComunikiMe.Web/Models/ErrorViewModel.cs
using System;

namespace TesteComunikiMe.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteComunikiMe.Web/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TesteComunikiMe.Application.Dtos;
using TesteComunikiMe.Web.Repositories;

namespace TesteComunikiMe.Web.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClienteRepository _clienteRepository;

        public ClientesController()
        {
            _clienteRepository = new ClienteRepository();
        }

        // GET: ClienteController
        public async Task<IActionResult> Index()
        {
            var clientes = await _clienteRepository.Get();

            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public async Task<IActionResult> Consultar(int id)
        {
            var cliente = await _clienteRepository.Get(id);

            return View(cliente);
        }

        // GET: ClienteController/Create
        public IActionResult Adicionar()
        {
            var cliente = new ClienteDto();

            return View(cliente);
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar(ClienteDto clienteDto)
        {
            if (ModelState.IsValid)
            {
                await _clienteRepository.Add(clienteDto);
                return RedirectToAction(nameof(Index));
            }
            else
                return View(clienteDto);
        }

        // GET: ClienteController/Edit/5
        public async Task<IActionResult> Editar(int id)
        {
            var cliente = await _clienteRepository.Get(id);

            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(ClienteDto clienteDto)
        {
            if (ModelState.IsValid)
            {
                await _clienteRepository.Update(clienteDto);
                return RedirectToAction(nameof(Index));
            }
            else
                return View(clienteDto);
        }

        // GET: ClienteController/Delete/5
        public async Task<IActionResult> Excluir(int id)
        {
            await _clienteRepository.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TesteComunikiMe.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TesteComunikiMe.Web.Models;

namespace TesteComunikiMe.Web.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteComunikiMe.Web/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TesteComunikiMe.Application.Dtos;
using TesteComunikiMe.Web.Repositories;

namespace TesteComunikiMe.Web.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly ProdutoRepository _produtoRepository;

        public ProdutosController()
        {
            _produtoRepository = new ProdutoRepository();
        }

        // GET: ProdutosController
        public async Task<ActionResult> Index()
        {
            var produtos = await _produtoRepository.Get();

            return View(produtos);
        }

        // GET: ProdutosController/Details/5
        public async Task<IActionResult> Consultar(int id)
        {
            var produto = await _produtoRepository.Get(id);

            return View(produto);
        }

        // GET: ProdutosController/Create
        public IActionResult Adicionar()
        {
            var produto = new ProdutoDto();

            return View(produto);
        }

        // POST: ProdutosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar(ProdutoDto produtoDto)
        {
            if (ModelState.IsValid)
            {
                await _produtoRepository.Add(produtoDto);
                return RedirectToAction(nameof(Index));
            }
            else
                return View(produtoDto);
        }

        // GET: ProdutosController/Edit/5
        public async Task<IActionResult> Editar(int id)
        {
            var produto = await _produtoRepository.Get(id);

            return View(produto);
        }

        // POST: ProdutosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(ProdutoDto produtoDto)
        {
            if (ModelState.IsValid)
            {
                await _produtoRepository.Update(produtoDto);
                return RedirectToAction(nameof(Index));
            }
            else
                return View(produtoDto);
        }

        // GET: ProdutosController/Delete/5
        public async Task<IActionResult> Excluir(int id)
        {
            await _produtoRepository.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TesteComunikiMe.Web/Controllers/VendasController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TesteComunikiMe.Application.Dtos;
using TesteComunikiMe.Web.Repositories;

namespace TesteComunikiMe.Web.Controllers
{
    public class VendasController : Controller
    {
        private readonly VendaRepository _vendaRepository;
        private readonly ClienteRepository _clienteRepository;
        private readonly ProdutoRepository _produtoRepository;

        public VendasController()
        {
            _vendaRepository = new VendaRepository();
            _clienteRepository = new ClienteRepository();
            _produtoRepository = new ProdutoRepository();
        }

        // GET: VendasController
        public async Task<ActionResult> Index()
        {
            var vendas = await _vendaRepository.Get();

            return View(vendas);
        }

        // GET: VendasController/Details/5
        public async Task<IActionResult> Consultar(int id)
        {
            var venda = await _vendaRepository.Get(id);

            return View(venda);
        }

        // GET: VendasController/Create
        public async Task<IActionResult> Adicionar()
        {
            var venda = new VendaDto();

            await FillViewBag();

            return View(venda);
        }

        private async Task FillViewBag()
        {
            ViewBag.Clientes = await _clienteRepository.Get();
            ViewBag.Produtos = await _produtoRepository.Get();
        }

        // POST: VendasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar(VendaDto vendaDto)
        {
            if (ModelState.IsValid)
            {
                await _vendaRepository.Add(vendaDto);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                FillViewBag();
                return View(vendaDto);
            }
        }

        // GET: VendasController/Edit/5
        public async Task<IActionResult> Editar(int id)
        {
            var venda = await _vendaRepository.Get(id);

            FillViewBag();

            return View(venda);
        }

        // POST: VendasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(VendaDto vendaDto)
        {
            if (ModelState.IsValid)
            {
                await _vendaRepository.Update(vendaDto);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                FillViewBag();
                return View(vendaDto);
            }
        }

        // GET: VendasController/Delete/5
        public async Task<IActionResult> Excluir(int id)
        {
            await _vendaRepository.Remove(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

TesteComunikiMe.Web/Views/Clientes/Adicionar.cshtml
@model TesteComunikiMe.Application.Dtos.ClienteDto

@{
    ViewData["Title"] = "Adicionar Cliente";
}

<h1>Adicionar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Adicionar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteComunikiMe.Web/Views/Clientes/Consultar.cshtml
@model TesteComunikiMe.Application.Dtos.ClienteDto

@{
    ViewData["Title"] = "Consultar Cliente";
}

<h1>Consultar Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    <a asp-action="Index">Voltar</a>
</div>

TesteComunikiMe.Web/Views/Clientes/Editar.cshtml
@model TesteComunikiMe.Application.Dtos.ClienteDto

@{
    ViewData["Title"] = "Editar Cliente";
}

<h1>Editar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteComunikiMe.Web/Views/Clientes/Index.cshtml
@using TesteComunikiMe.Utilities.Consts
@model IEnumerable<TesteComunikiMe.Application.Dtos.ClienteDto>

@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Adicionar">Adicionar</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sobrenome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Consultar", "Consultar", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.Id }, new { onclick = $"return confirm('{Mensagens.ConfirmaExclusao}');" })
                </td>
            </tr>
        }
    </tbody>
</table>
<center><h6>@($"{Model.Count()} {Mensagens.RegistrosEncontrados}")</h6></center>

TesteComunikiMe.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TesteComunikiMe.Web/Views/Produtos/Adicionar.cshtml
@model TesteComunikiMe.Application.Dtos.ProdutoDto

@{
    ViewData["Title"] = "Adicionar Produto";
}

<h1>Adicionar Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Adicionar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteComunikiMe.Web/Views/Produtos/Consultar.cshtml
@model TesteComunikiMe.Application.Dtos.ProdutoDto

@{
    ViewData["Title"] = "Consultar Produto";
}

<h1>Consultar Prodto</h1>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadeEstoque)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuantidadeEstoque)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    <a asp-action="Index">Voltar</a>
</div>

TesteComunikiMe.Web/Views/Produtos/Editar.cshtml
@model TesteComunikiMe.Application.Dtos.ProdutoDto

@{
    ViewData["Title"] = "Editar Produto";
}

<h1>Editar Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteComunikiMe.Web/Views/Produtos/Index.cshtml
@using TesteComunikiMe.Utilities.Consts
@model IEnumerable<TesteComunikiMe.Application.Dtos.ProdutoDto>

@{
    ViewData["Title"] = "Produtos";
}

<h1>Produtos</h1>

<p>
    <a asp-action="Adicionar">Adicionar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantidadeEstoque)
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuantidadeEstoque)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Consultar", "Consultar", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.Id }, new { onclick = $"return confirm('{Mensagens.ConfirmaExclusao}');" })
                </td>
            </tr>
        }
    </tbody>
</table>
<center><h6>@($"{Model.Count()} {Mensagens.RegistrosEncontrados}")</h6></center>

TesteComunikiMe.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste Comuniki.me</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteComunikiMe.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Vendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TesteComunikiMe.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TesteComunikiMe.Web/Views/Vendas/Adicionar.cshtml
@using TesteComunikiMe.Application.Dtos
@model TesteComunikiMe.Application.Dtos.VendaDto

@{
    ViewData["Title"] = "Adicionar Venda";
}
<script>
    $(function () {
        $('name="AdicionarProduto"').click(function () {

        });
    });
</script>
<h1>Adicionar Venda</h1>

<h4>Venda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Adicionar">
            <div asp-validation-summary="ModelOnly" class="text-danger" />
            <div class="form-group">
                <label asp-for="Cliente" class="control-label" />
                <select asp-for="Cliente">
                    @foreach (var item in ViewBag.Clientes)
                    {
                        <option value="@item">@($"{item.Nome} {item.Sobrenome}")</option>
                    }
                </select>
                <span asp-validation-for="Cliente" class="text-danger" />
            </div>
            <div class="form-group">
                <h6>@Html.DisplayNameFor(p => p.VendaDetalhes)</h6>
                <hr />
                @foreach (var item in ViewBag.Produtos as List<ProdutoDto>)
                {
                    <div class="form-group">
                        <label class="control-label">@item.Descricao</label>
                        <label class="control-label">Quantidade</label>
                        <input type="number" name="QuantidadeProduto" class="form-control" />
                        <input name="AdicionarProduto" data-produto="@item" type="button" value="Adicionar" class="btn btn-primary" />
                    </div>
                }
            </div>
            <h6>Carrinho de Compras</h6>
            <hr />
            <div class="form-group">
                <table id="@Html.IdFor(p => p.VendaDetalhes)" name="@Html.NameFor(p => p.VendaDetalhes)" class="table">
                    <thead>
                        <tr>
                            <th>
                                Descrição
                            </th>
                            <th>
                                Quantidade
                            </th>
                            <th>
                                Valor Total
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.VendaDetalhes)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Produto.Descricao)
                                </td>
                                <th>
                                    @Html.DisplayFor(modelItem => item.Quantidade)
                                </th>
                                <th>
                                    @Html.DisplayFor(modelItem => item.ValorTotal)
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteComunikiMe.Web/Views/Vendas/Consultar.cshtml
@using TesteComunikiMe.Utilities.Consts
@model TesteComunikiMe.Application.Dtos.VendaDto

@{
    ViewData["Title"] = "Consultar Venda";
}

<h1>Consultar Venda</h1>

<div>
    <h4>Venda</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Nome)
            @Html.DisplayFor(model => model.Cliente.Sobrenome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Descrição
                </th>
                <th>
                    Quantidade
                </th>
                <th>
                    Valor Total
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.VendaDetalhes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Descricao)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.ValorTotal)
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    <a asp-action="Index">Voltar</a>
</div>